
CREATE TABLE payment(
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name character varying(255) NOT NULL,
	last_name character varying(255) NOT NULL,
	zip_code character varying(32) NOT NULL,
	card_number character varying(16) NOT NULL,
	created_at timestamp without time zone
);

CREATE TABLE payment_webhook(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    notification_url character varying(255) NOT NULL,
    created_at timestamp without time zone
);

